export const CLOTHES_LIST_REQUEST = "CLOTHES_LIST_REQUEST";
export const CLOTHES_LIST_SUCCESS = "CLOTHES_LIST_SUCCESS";
export const CLOTHES_LIST_FAIL = "CLOTHES_LIST_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
